### ISSUE TITLE
Front-end checklist

### ISSUE THREAD

**Issue by jasonou1994** [getswell/getswell#147]
For each of the following, does it properly display formatted 

HTTP1.1 / Plain Response
Request
- [x] Headers
- [ ] Cookies
- [x] Body

Response
- [x] Headers
- [x] Cookies
- [ ] Body - plain string
- [ ] Body - JSON
- [x] Body - HTML/JS

HTTP1.1 / SSE
Request
- [x] Headers
- [ ] Cookies
- [x] Body

Response
- [x] Headers
- [x] Cookies
- [x] Events

HTTP2 / Plain Response
Request
- [x] Headers
- [ ] Cookies
- [x] Body

Response
- [x] Headers
- [x] Cookies
- [ ] Body - plain string
- [ ] Body - JSON
- [x] Body - HTML/JS

HTTP2 / SSE
Request
- [x] Headers
- [ ] Cookies
- [x] Body

Response
- [x] Headers
- [x] Cookies
- [x] Events
